### ISSUE TITLE
Add the feature of Register/login using similar tech stack only[GUI]

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#1]

**Comment by Swap-Nova** [comment]
Hey, I have little experience with Tkinter. Can I help you out by adding the feature of register/login?

**Comment by Pranjal360Agarwal** [comment]
Sure, go ahead with the issue and try to develop the solution.
@Swap-Nova 
All the best!!

**Comment by Swap-Nova** [comment]
Thanks :))

**Comment by Swap-Nova** [comment]
Sent you a PR. Please do look into it.
