### ISSUE TITLE
New logo 

### ISSUE THREAD

**Issue by Abhinavcode13** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#105]
I want to give a new design to the logo as it is not visually appealing that much . please assign me this @Pranjal360Agarwal .

**Comment by Deepti20211** [comment]
I want to give a new design to the logo. please assign me this @Pranjal360Agarwal .

**Comment by Abhinavcode13** [comment]
please do check @Pranjal360Agarwal

**Comment by HartzFrequency** [comment]
hi @Pranjal360Agarwal you can assign it to me if it is not done yet I will create the new logo and then integrate it in the python source code
