### ISSUE TITLE
Found some issue in the database - bonus points who can resolve!!

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#106]
**There is some error in the database, on selecting cities, no bus is available.**

Either create a new database adding some cities, but prepare a Word document that has all the details of the entries.
or resolve the existing database.
If anyone can correct it, ping me back here, and I will assign it to the level 3 GSSOC category!!

Extra points will be there.

**Comment by Abhinavcode13** [comment]
please assign me this issue @Pranjal360Agarwal

**Comment by Pranjal360Agarwal** [comment]
> please assign me this issue @Pranjal360Agarwal

If resolved, will get extra bonus points for sure!!

**Comment by HartzFrequency** [comment]
Please assign me also for this work @Pranjal360Agarwal

**Comment by Vedansh-777** [comment]
Please assign me this issue GSSoS'23 @Pranjal360Agarwal

**Comment by Pranjal360Agarwal** [comment]
@Vedansh-777 like I choose Bhopal to Guna one 1-12-2022 it is not showing any buses, instead the database has it

**Comment by Vedansh-777** [comment]
@Pranjal360Agarwal Yes, I have noticed that if we type manually, it gives the correct buses from the database. That's why I asked earlier to give an example. By the way, thanks for helping us. We'll work on it.

**Comment by Pranjal360Agarwal** [comment]
@Vedansh-777 yeah that's the issue

**Comment by sagnik-p** [comment]
This thread has been inactive for a long time
I would like to work on this
Please assign
