### ISSUE TITLE
[GSSoC 23'] Adding Receipt Generation

### ISSUE THREAD

**Issue by HartzFrequency** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#110]
Hi, @Pranjal360Agarwal! I'm looking to incorporate a feature that generates receipts. Specifically, I want to create a mechanism that generates a receipt in both GUI and TXT formats.

**Comment by Pranjal360Agarwal** [comment]
Yeah that will be an useful feature!!
