### ISSUE TITLE
[GSSOC '23] Form validation During registration and login[BUG!]

### ISSUE THREAD

**Issue by slayerrr12** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#114]
Hii @Pranjal360Agarwal 
There was a bug in the sign in page module . The user is able to register itself even if the password fields are empty .
So i wanted to add form validation feature in the signup page . I will also be adding some constraint/validation for password as well which will force the user to enter a certain length of password
 please assign me this issue I would be very happy to contribute.

**Comment by Pranjal360Agarwal** [comment]
Already resolved

**Comment by slayerrr12** [comment]
the current version of the code does'nt have it i had checked it when i ran it @Pranjal360Agarwal
