### ISSUE TITLE
[GSSoC 23'] Creating User Dashboard 

### ISSUE THREAD

**Issue by HartzFrequency** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#126]
Hi @Pranjal360Agarwal I want to create a dashboard for user where your details are listed and you can see your booked tickets and more additional features

**Comment by prashant226** [comment]
i can work on this can u assign it to me under gssoc'23

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by Pranjal360Agarwal** [comment]
@HartzFrequency Any help u need?
Since it has been 2 weeks on this issue, do u need more time or any issue u are facing?

**Comment by HartzFrequency** [comment]
hello @Pranjal360Agarwal ,
Apologies for the delay. I am currently on a road trip with my family, and the issue is taking a bit longer than expected. However, I assure you that I will complete the task as soon as possible.
At the moment, I am focusing on addressing the issues which are of data addition. I am actively working on this and will submit a pull request (PR) as quickly as I can.

**Comment by Pranjal360Agarwal** [comment]
@HartzFrequency No worries, enjoy your trip!!
You have already worked on various features, you can take your time.

**Comment by HartzFrequency** [comment]
Hello @Pranjal360Agarwal, I have completed the UI work. Can I proceed to raise the pull request? I will start integrating it with the database as soon as I arrive at the home.

**Comment by Pranjal360Agarwal** [comment]
Great @HartzFrequency!!

**Comment by HartzFrequency** [comment]
Hello, @Pranjal360Agarwal! I've finished developing the graphical user interface (GUI) for the dashboard. Can I submit a pull request (PR) to integrate some additional features? However, implementing some features of the dashboard would require significant modifications to multiple sections of the code, so I plan to create a separate issue for that after submitting this PR.

**Comment by Pranjal360Agarwal** [comment]
@HartzFrequency You can go anyway, I will label all your issues, PRs - no worries.
Just be sure that project after the integration of PR is working fine.

**Comment by Pranjal360Agarwal** [comment]
@HartzFrequency what exact features have u developed , just mention in the PR/issue when raising.

**Comment by HartzFrequency** [comment]
@Pranjal360Agarwal Please open this issue
