### ISSUE TITLE
Adding a booking history page

### ISSUE THREAD

**Issue by Bhumika79** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#130]
By accessing this feature, the user can view his ticket booking history and compare and go through all the relevant information he needs from past bookings and apply them to the present bookings; or he can go through his previous bookings using this section.

**Comment by Pranjal360Agarwal** [comment]
@Bhumika79 Why a user need to have previous billing details?

**Comment by Pranjal360Agarwal** [comment]
The ticket will be printed, it can be too referred
