### ISSUE TITLE
Migrate the Entire Codebase to a Python Module

### ISSUE THREAD

**Issue by pooranjoyb** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#131]
## Issues : 
The folder or directory structuring for the project is not organized properly.

## FIX : 
-  A serious migration and proper structuring of the project is needed.
-  Need to use ```.gitignore``` to ignore some basic static files
-  Add a separate ``src`` directory for the frontend. Backend Directories should be separate.
-  There's also no `requirement.txt` for the proper installation of the **modules & packages**, the user has to manually install all the required packages to get the project working.
-  Assets should be kept separate in a public directory.

Would be glad if you assign these issues to me under **GSSoC '2023**.  @Pranjal360Agarwal

**Comment by Pranjal360Agarwal** [comment]
@pooranjoyb Make sure to maintain the integrity of the project!!

**Comment by pooranjoyb** [comment]
> @pooranjoyb Make sure to maintain the integrity of the project!!

Sure :rocket:
