### ISSUE TITLE
Buttons are not properly aligned!!

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#133]
When selecting the seat, the page is not properly aligned with the buttons.

**Comment by Pranjal360Agarwal** [comment]
Anyone can resolve this issue?

**Comment by HartzFrequency** [comment]
please assign that to me @Pranjal360Agarwal

**Comment by SimranLahrani842** [comment]
> Anyone can resolve this issue?

Assign me this issue @Pranjal360Agarwal sir

**Comment by HartzFrequency** [comment]
hey @Pranjal360Agarwal can you please share some snapshots of problem I'm unable to understand the issue

**Comment by Pranjal360Agarwal** [comment]
![Screenshot 2023-05-26 235140](https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/assets/98935622/bb645c4b-cd83-48f0-a623-166badc4d215)

**Comment by Pranjal360Agarwal** [comment]
the text and buttons are not properly aligned @HartzFrequency 
this needs to be fixed.
