### ISSUE TITLE
[GSSoC 23'] Creating A POP-UP modern GUI to show Available Buses

### ISSUE THREAD

**Issue by HartzFrequency** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#139]
hey @Pranjal360Agarwal,

I aim to design a unique and contemporary graphical user interface (GUI) that incorporates a scrolling functionality for presenting bus data, while also preserving all current options. Additionally, I intend to introduce new features such as a drop-down menu for selecting buses, among others, and then redirecting to the home GUI.

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
