### ISSUE TITLE
Create the Presentation of the project

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#14]
Take the screeenshots of all the pages of the project, then attach them in a single ppt, first page should contain the name of the porject with the tech stacks used!!

**Comment by Nupoor10** [comment]
Hey! I would like to  work on this for Kwoc

**Comment by Pranjal360Agarwal** [comment]
**Go for it!!** @Nupoor10

**Comment by Pranjal360Agarwal** [comment]
Join this channel[official] for more details for contributing in it:-
https://discord.gg/JdGM4MTG

**Comment by Nupoor10** [comment]
Hey I have made a PR regarding this issue. I have prepared the PPT using Google Slides. Please let me know if there are any issues/changes!

**Comment by Pranjal360Agarwal** [comment]
@Nupoor10 **Great work done.**
