### ISSUE TITLE
Need for adding requirements file

### ISSUE THREAD

**Issue by okaditya84** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#146]
The execution of project will be made easier if this project has a requirements.txt file.
The need occurs because it's a big project.
I will added a file that will contain all the libraries and dependencies needed to execute the project.

**Comment by Pranjal360Agarwal** [comment]
Go with it!!

**Comment by okaditya84** [comment]
> Go with it!!

Did you merge my PR ?
