### ISSUE TITLE
A fresh, modern GUI For the application

### ISSUE THREAD

**Issue by 2004satwik** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#150]
### Is your feature request related to a problem? Please describe.

Hello! I found that this application needs a clear and professional looking GUI, as the current interface is not quit good and widgets are not aligned properly.

### Describe the solution you'd like

 i just came up with the idea of making the GUI completely realistic and modern using Qt modules. This gives the software a professional  look and also increases the user experience. However, all the options will be kept the same.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 2004satwik** [comment]
Please consider this issue and assign this to me

**Comment by Pranjal360Agarwal** [comment]
@2004satwik Is your work done, since it has more than 2 weeks?

**Comment by pavitraag** [comment]
I am interested to work on this can u assign me this under gssoc'23
