### ISSUE TITLE
New Logo for this project that will represent it.

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#156]
### Is your feature request related to a problem? Please describe.

Anyone want to work on this issue can ping me here.

### Describe the solution you'd like

I will assign the issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SargamPuram** [comment]
Yes , I can do that . Kindly assign it to me under GSSOC'23.
Also , after creating the logo ,
Should I add the file in the bus-booking-system folder image sub folder and then create pr?

**Comment by Pranjal360Agarwal** [comment]
yeah sure

**Comment by Pranjal360Agarwal** [comment]
ping in the comments of that issue

**Comment by SargamPuram** [comment]
Yes , I can do that . Kindly assign it to me under GSSOC'23.
Also , after creating the logo ,
Should I add the file in the bus-booking-system folder image sub folder
and then create PR?

**Comment by SargamPuram** [comment]
What are your thoughts about this one?
![APNA-BHARAT BUS BOOKING SYSTEM](https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/assets/130867468/05079ffa-178d-47de-b7d9-522672a21879)

**Comment by Pranjal360Agarwal** [comment]
yeah @SargamPuram it depicts the meaning.
Raise the PR, add this in the readme file and placed this image in (https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/tree/master/bus-booking-system) i9mage folder

/Image

**Comment by Pranjal360Agarwal** [comment]
@SargamPuram

**Comment by SargamPuram** [comment]
> yeah @SargamPuram it depicts the meaning. Raise the PR, add this in the readme file and placed this image in (https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/tree/master/bus-booking-system) i9mage folder
> 
> /Image

@Pranjal360Agarwal yes I'll do that .And raise the PR .
Can you assign me this and also add the gssoc'23 label
