### ISSUE TITLE
Standard passwords creation during the registeration

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#157]
### Is your feature request related to a problem? Please describe.

yes for security purposes

### Describe the solution you'd like

like certain digits in it, certain special characters in it, atleast one capital etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shrey141102** [comment]
Standard passwords creation - we can make like an automatic password suggester for the user? and also like a type of checking mechanism that the password entered by user has at-least 1 uppercase, lowercase, number and special character?

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by shrey141102** [comment]
Hi bro, i have already put forward a pull request. Am waiting for admin to merge it
