### ISSUE TITLE
Website link not working

### ISSUE THREAD

**Issue by SimranLahrani842** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#167]
### Describe the bug

The given link shows 404 error and is not working when clicking.

### Expected behaviour

While opening the link given in attachments it shows 404 error.Please let me know how to solve this issue so that I can update it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pranjal360Agarwal** [comment]
To run this project, no need of link, just run the main.py file

I will soon remove the link
