### ISSUE TITLE
Password authentication 

### ISSUE THREAD

**Issue by SimranLahrani842** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#168]
### Is your feature request related to a problem? Please describe.

Making website more secure by creating a password which is authenticated.

### Describe the solution you'd like

Password if simple can be hacked therefore creating a password with few restrictions makes it hard to crack.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimranLahrani842** [comment]
> 👋 @SimranLahrani842 This issue is closed.

Y closed?

**Comment by Pranjal360Agarwal** [comment]
@SimranLahrani842 Since it has been solved.
