### ISSUE TITLE
Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#187]
*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@Pranjal360Agarwal please assign me this issue under gssoc'23.

**Comment by Pursottam6003** [comment]
Hii @Pranjal360Agarwal  can you please help me how to start the server locally? I was following the Contribution.MD file https://github.com/Pursottam6003/ApnaBharat-Bus-Booking-Reservation-System/blob/master/CONTRIBUTING.md but there is no further information on how to run the server 

Can you help me with what to do next after cloning and creating a branch?
