### ISSUE TITLE
Modification of readme.md

### ISSUE THREAD

**Issue by barkhaaroraa** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#196]
### Describe the bug

the open source programs this repo has been a part of has been mentioned twice in the readme.md file which isn't required. 
so i'd like to remove the first mention and keep the one with the posters of the programs

### Expected behaviour

the open source programs should only be mentioned once.

### Screenshots

<img width="717" alt="image" src="https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/assets/115429121/e9842146-e71f-4abb-86cc-bee346efafc1">
<img width="794" alt="image" src="https://github.com/Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System/assets/115429121/dca1ed11-194a-48e0-bd87-09e7596b2f27">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pranjal360Agarwal** [comment]
@barkhaaroraa there are three separate open source program mentioned as well as in the posters already.

**Comment by barkhaaroraa** [comment]
my issue was about the first mention. so in the entire readme.md file the open source programs are mentions twice at two totally different locations. so the idea that i was proposing was that you should remove the first mention( the one with the hearts ) as all of the open source programs are already mentioned at the end with their posters

**Comment by Pallavi-star2002** [comment]
I want work for this issue .Can you please assign me ? I am particiapnt of GSSOC'23.
