### ISSUE TITLE
Add the seat matrix feature similar to what we see in Redbus app

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#2]

**Comment by hDmtP** [comment]
Hey, can I contribute to this issue under KWoC 2022?

**Comment by Pranjal360Agarwal** [comment]
Join this channel[official] for more details for contributing in it:-
https://discord.gg/JdGM4MTG

**Comment by hDmtP** [comment]
I have.

**Comment by ManasviEmmadi** [comment]
@Pranjal360Agarwal could you assign this issue to me?

**Comment by Arnab7456** [comment]
can you assign me this problem

**Comment by kdotambuj** [comment]
Can you assign me to contribute to this issue? I'm a contributor in GSSOC 2023.

**Comment by Vedansh-777** [comment]
I GSSOC 2023 Contributor would be delighted to contribute to the implementation of this feature. @Pranjal360Agarwal

**Comment by gp0814** [comment]
@Pranjal360Agarwal 
I'm GSSoc 23 contributor
I want to work on this issue
Please assign this to me.
