### ISSUE TITLE
User dashboard

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#222]
### Is your feature request related to a problem? Please describe.

Similar to Redbus profile section.

### Describe the solution you'd like

Details such as their history of booking, payment done, etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prashant226** [comment]
please assign this issue to me

**Comment by lavi20** [comment]
please assign this issue to me
