### ISSUE TITLE
seat booking probability predictor

### ISSUE THREAD

**Issue by hemant933** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#227]
### Is your feature request related to a problem? Please describe.

we can add a booking probability generator which shows the chances of seat booking , this will help the user to check which bus have highest booking chances.

### Describe the solution you'd like

we can use naive bayes model on booking data , which is begin stored in database to predict the confirmation chances.

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by Pranjal360Agarwal** [comment]
@hemant933 That's any amazing idea, go ahead to implement it!

**Comment by hemant933** [comment]
okay

**Comment by hemant933** [comment]
i created a PR for this.

**Comment by Pranjal360Agarwal** [comment]
> i created a PR for this.
Try to integrate this feature in the exisiting project, then again create the PR.
