### ISSUE TITLE
Strong Password Standards Enforcements during registration (With random password generator facility)

### ISSUE THREAD

**Issue by Sapt-pal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#26]
## Implementing a python snippet to ensure strong password standards enforcement during registration.

- Informing users of strong password standards guidelines as recommended by international cybersecurity experts

- Random password generator facility available based on user input

- If custom password set, checking whether password meets recommended security standards

**Comment by ManasviEmmadi** [comment]
@Sapt-pal i would like to work on this issue.

**Comment by Codeblade98** [comment]
Can I be assigned this issue pls

**Comment by Sapt-pal** [comment]
> @Sapt-pal i would like to work on this issue.

Sure @ManasviEmmadi we can work together on this!

**Comment by Pranjal360Agarwal** [comment]
@Sapt-pal @ManasviEmmadi Work upon this issue, integrate with the project asap

**Comment by Sapt-pal** [comment]
Hi @Pranjal360Agarwal thanks for assigning me this issue, I have the last
mid-sem exam tomorrow, and from evening onwards I shall be able to give
full time on KWoC.

Btw can you please check this < https://github.com/Sapt-pal/Py_Passcred >
and see whether the same algo can be applied here?
Obviously I will need to customize this algo according to the current
project.

Saptarshi Pal

**Comment by Pranjal360Agarwal** [comment]
@Sapt-pal No problem work upon as per your time.
No need to give preference for this.
Totally understand the situation!!

**Comment by Sapt-pal** [comment]
Thank you for understanding! : )
