### ISSUE TITLE
Add the station to station data like dynamic seat booking availability

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#3]

**Comment by Garvit414** [comment]
Please guide me regarding this issue. I want to contribute to this issue under KWoC.

**Comment by Pranjal360Agarwal** [comment]
Join this channel[official] for more details for contributing in it:- 
https://discord.gg/JdGM4MTG

**Comment by Garvit414** [comment]
@Pranjal360Agarwal Thanks for assigning me this issue, but I am currently unable to work on it. So, you can unassign me so that other contributors can contribute to this issue. I will definitely contribute to your project later.

**Comment by Pranjal360Agarwal** [comment]
Sure

**Comment by devichand579** [comment]
I want to work on this issue under Kwoc. Please guide me regarding the issue

**Comment by Pranjal360Agarwal** [comment]
@devichand579 you need to update the existing codes so that it can take multiple seat bookings even small to big stations,
i.e you need to add some tables in it the database.

**Comment by devichand579** [comment]
do I need to create a table in database having the station to station data like dynamic booking and some other features as columns ?

**Comment by devichand579** [comment]
I.e ,showing the availability ,distance,time of travel ...these kind of features
