### ISSUE TITLE
Add the dynamic fare for in between stations for small route

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#4]

**Comment by Pranjal360Agarwal** [comment]
Go with this issue and try to develop the solutions.

For more details, join the channel:- https://app.slack.com/huddle/TQN1S8HGF/C04DYCVEY5R

**Comment by Pranjal360Agarwal** [comment]
Join this channel[official] for more details for contributing in it:- 
https://discord.gg/JdGM4MTG

**Comment by blip100** [comment]
Can I be assigned this issue as a part of KWoC 2022 and could you please guide me on how to proceed about it.

**Comment by Pranjal360Agarwal** [comment]
@blip100 need to add new tables in database for this feature.
