### ISSUE TITLE
Strong Password Standards Enforcements during registration

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#46]
## Implementing a python snippet to ensure strong password standards enforcement during registration.

- Informing users of strong password standards guidelines as recommended by international cybersecurity experts

- Random password generator facility available based on user input

- If custom password set, checking whether password meets recommended security standards

**Comment by Bharadwajshivam28** [comment]
I have created it sir @Pranjal360Agarwal

**Comment by Bharadwajshivam28** [comment]
assign it to me

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 I have already closed an issue created by you related to this only

I was not assigned

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 I have already closed an issue created by you related to this only

I am making a issue assign me and give iwoc tag with difficult tag also

**Comment by yaminimasand** [comment]
I can do it. Kindly assign it to me.

**Comment by yaminimasand** [comment]
Thank you. Will start working on this issue.
