### ISSUE TITLE
New Feature in interface wise and functionality

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#48]
If one needs to add any new feature that will enhance the existing project, raise the issue, please open it and tag me I will verify, then assign you.

**Comment by bishalde** [comment]
I would like to Update the Design of this application [Final.py] to make is responsive...! 

And want to include some features like.
1. Available Bus Timetable chart.
2. Private Bus booking.
3. customer support.
4. Admin Dashboard.

please assign me this task under GSSOC-2023

**Comment by NIveX2169** [comment]
This is my first time contributing in open source ,I want to add weather of destination during selection of journey ....please assign me

**Comment by Pranjal360Agarwal** [comment]
@NIveX2169 go with it
