### ISSUE TITLE
Update the Contributorslist.js file

### ISSUE THREAD

**Issue by Pranjal360Agarwal** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#5]
One can start their open source journey by raising their first **PR** by just updating their details in **Contributorslist.js file**.

**Comment by shrey141102** [comment]
I'll do

**Comment by yashpatel08** [comment]
Yash  Patel 
https://github.com/yashpatel08

**Comment by yashpatel08** [comment]
i have make the changes in the contributors list please check it tell me if
it is ok ASAP

**Comment by AnishSingh5665** [comment]
I want to work on it so please guide me on what to update I will do it.

**Comment by shrey141102** [comment]
@AnishSingh5665 You need to add your details in the above mentioned file and make a pull req

**Comment by devichand579** [comment]
done

**Comment by Dragonstac** [comment]
@Pranjal360Agarwal I can do it

**Comment by Anubhavsoni001** [comment]
@Pranjal360Agarwal please assign me I wanna solve this.

**Comment by Serve-er** [comment]
please assign it to me

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal Hello sir i can make it the best one please just give me a chance

**Comment by Bharadwajshivam28** [comment]
thanks sir @Pranjal360Agarwal

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal sir can you suggest that which sections you want to be updated

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal sir issue please elaborate the issue

**Comment by Bharadwajshivam28** [comment]
basically i guess i have to add my deatils in that file

**Comment by Pranjal360Agarwal** [comment]
look at the previous PR @Bharadwajshivam28

**Comment by Pranjal360Agarwal** [comment]
Star the repo, edit that file and raise the PR

**Comment by Bharadwajshivam28** [comment]
ok

**Comment by Bharadwajshivam28** [comment]
sir i understood that

**Comment by Bharadwajshivam28** [comment]
but in js file i ahve to add my name,gtihub link and linkdin lin

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal or something else

**Comment by Pranjal360Agarwal** [comment]
yes

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Pranjal360Agarwal** [comment]
just only this only

**Comment by A91y** [comment]
Please assign me this issue.

**Comment by Nandani14** [comment]
@Pranjal360Agarwal I also want to contribute to this . PLease assign this to me

**Comment by Bharadwajshivam28** [comment]
thanks alot sir @Pranjal360Agarwal
