### ISSUE TITLE
Improvements 

### ISSUE THREAD

**Issue by ShubhAgarwal-0704** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#53]
Improve the language of Presentation i.e. "ApnaBharat-Bus-Booking-Reservation-System" for the ease of understanding for the 1st time contributors.

**Comment by Pranjal360Agarwal** [comment]
Share the ppt file with google drive link here in comments before I can merge. @ShubhAgarwal-0704

**Comment by ShubhAgarwal-0704** [comment]
Hey, Thanks for following up, I have tried to use pointers in the ppt for
better understanding , If you need any further changes please let me know.

Here is the link of Google drive.....

https://docs.google.com/presentation/d/104IwnfIzweevCbUM5KpaBjTwVkGWOq_3/edit?usp=sharing&ouid=110287478605196894421&rtpof=true&sd=true
