### ISSUE TITLE
Hindi Readme for multilinguals

### ISSUE THREAD

**Issue by A91y** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#60]
New Readme can be written in Hindi to help multilinguals.

**Comment by A91y** [comment]
Please assign me this issue under iwoc and easy/medium/hard.

**Comment by Pranjal360Agarwal** [comment]
@A91y In this case , create a separate file for it and in the actual readme file of the project, mention a special link to that file
