### ISSUE TITLE
Creating a new login/signup box

### ISSUE THREAD

**Issue by Bharadwajshivam28** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#66]
If sir there will be a login/signup box then it will be good

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal

**Comment by Pranjal360Agarwal** [comment]
Many of the contributors have tried to make it but yet not merged with the project at the starting page, that's the big issue!!
@Bharadwajshivam28 
if you can merge it, then go for it!!

**Comment by Bharadwajshivam28** [comment]
> Many of the contributors have tried to make it but yet not merged with the project at the starting page, that's the big issue!!
> @Bharadwajshivam28 
> if you can merge it, then go for it!!

Can you drop me the live link of project

**Comment by Pranjal360Agarwal** [comment]
@Bharadwajshivam28 for wokring you can open the project in vscode(python) and run it, it will start the project and there is one ppt in the project too for refereence

**Comment by Bharadwajshivam28** [comment]
ya its done

**Comment by Bharadwajshivam28** [comment]
sir but here it is one signup/login box created

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-02-22 16-42-43](https://user-images.githubusercontent.com/108119109/220604373-b0324663-de14-4bed-aad4-aa85354a52fb.png)

**Comment by Bharadwajshivam28** [comment]
its this one

**Comment by Bharadwajshivam28** [comment]
@Pranjal360Agarwal so bascially the code will be in this file of like its named as login.html

**Comment by Bharadwajshivam28** [comment]
sir the changes will be made in this file like login.html
