### ISSUE TITLE
Front end or backend 

### ISSUE THREAD

**Issue by SimranLahrani842** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#82]
As I m new to it assign me a issue that could be solved ,i would like to contribute in your repo.

**Comment by mridul45** [comment]
I would be happy to contribute as a Backend developer.

**Comment by Pranjal360Agarwal** [comment]
> As I m new to it assign me an issue that could be solved, I would like to contribute to your repo.

@SimranLahrani842 There are various issues opened, you can check them out or if u want create a new issue!!

**Comment by Pranjal360Agarwal** [comment]
> I would be happy to contribute as a Backend developer.

A good option, try to increase the database of the project to a wide portion. @mridul45

**Comment by mridul45** [comment]
Thx for the opportunity

**Comment by mridul45** [comment]
Hi Pranjal I have cloned the repo , but if it's okay then can I start the work on the project by 27th as my exams are on the way.
