### ISSUE TITLE
change description of the readme.md file

### ISSUE THREAD

**Issue by sandeep0009** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#84]
i found that i could write much better description of your readme.md file so please provide me this issue under gssoc 23

**Comment by jishu04** [comment]
Hey I can add and modify the description and make it look more better and authentic ,provide me the privilege to solve the issue under GSSOC'23

**Comment by Sayan2k3** [comment]
Hey I can modify and add a proper lined and attractive  description (readme.md.file) for your venture ,it would be great opportunity for me if you can assign the issue to me under the program of GSSOC'23

**Comment by MeMeee1** [comment]
Hello
I would like to take on this issue and work on creating a better description for the readme.md file under GSSoC'23. I believe a well-written and informative readme is crucial for the project's success. 

Looking forward to contributing to the project!

**Comment by dikshapadi** [comment]
Can someone please help me out with running this project?
the libraries to be installed(if any) and steps to follow to run the project!
