### ISSUE TITLE
Add Login for Admin Only page

### ISSUE THREAD

**Issue by hemansh** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#85]
Hi, I can add proper Login and Register page to prevent unauthorized access to admin only page.
please assign me this issue under Gssoc23

**Comment by akashg001** [comment]
Hi, @Pranjal360Agarwal  I can add proper Login page to prevent unauthorized access to admin only page. i have already work on this multiple times and can easily deliver on time.
please assign this issue me this issue under Gssoc23
