### ISSUE TITLE
To add features and Modify GUI.!

### ISSUE THREAD

**Issue by bishalde** [Pranjal360Agarwal/ApnaBharat-Bus-Booking-Reservation-System#91]
I would like to Update the Design of this application [Final.py] to make is responsive...!

And want to include some features like.

Available Bus Timetable chart.
Private Bus booking.
customer support.
Admin Dashboard.

please assign me this task under GSSOC-2023

**Comment by priyanshiee** [comment]
Thankyousomuchh!!

**Comment by sujithm21** [comment]
I would like to enhance the GUI to a good extent and add more functionalities using sqlite3 to make the application more interactive and good looking and have a good backend with manageable concurrent transactions.

**Comment by NISHIKA-17** [comment]
I am thrilled to be here and excited to contribute to GUI development! I have a passion for creating intuitive and visually appealing interfaces that enhance user experiences. I am eager to learn and grow in this field, and I appreciate any guidance and support from all of you. Let's collaborate and create some amazing GUI features .

**Comment by Pranjal360Agarwal** [comment]
@sujithm21 @priyanshiee @NISHIKA-17 @bishalde anyone have worked on this issue?  since any issue can't be open for such such long time.

**Comment by bishalde** [comment]
Yes i am working on this, and will be completing it by this weekend.!

**Comment by Pranjal360Agarwal** [comment]
@bishalde yeah sure, you can raise PR. by this weekend.!
Take your time.
